# Generated by Django 4.2.7 on 2023-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('short_url', models.URLField(unique=True, verbose_name='Короткая ссылка')),
            ],
        ),
    ]
